version: '3.8'

services:
  server:
    container_name: server
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 6450  # не нужно наружу, только внутри сети

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server


#services:
#  server:
#    container_name: server
#    build: 
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 3000:6450